// // This file was automatically generated by 'Kmisc::registerFunctions()'
// 
// #include <Rinternals.h>
// #include "RcppExports.cpp"
// #include <R_ext/Rdynload.h>
// 
// SEXP fitBinomialTestHMMcontextTransition(SEXP counts_totalSEXP, SEXP counts_methSEXP, SEXP contextSEXP, SEXP transitionContextSEXP, SEXP distancesSEXP, SEXP paramsSEXP, SEXP algorithmSEXP);
// SEXP cleanup();
// 
// R_CallMethodDef callMethods[]  = {
//   {"C_fitBinomialTestHMMcontextTransition", (DL_FUNC) &fitBinomialTestHMMcontextTransition, 7},
//   {"C_cleanup", (DL_FUNC) &cleanup, 0},
//   {NULL, NULL, 0}
// };
// 
// void R_init_methimpute(DllInfo *info) {
//   R_registerRoutines(info, NULL, callMethods, NULL, NULL);
//   R_useDynamicSymbols(info, FALSE);
// }
// 
